# Generated by Django 5.0.6 on 2026-05-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
