# Generated by Django 5.0.6 on 2026-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_drivefile_description_drivefile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='google_drive_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='web_view_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
